### DISPLAYS ONE ACTOR
POST http://localhost:3000/actors/23.json
Content-Type: application/json



### CREATES ACTOR
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Christian",
  "last_name": "Bale",
  "known_for": "American Psycho"
}

### UPDATES ACTOR
PATCH http://localhost:3000/actors/11.json
Content-Type: application/json

{
  "first_name": "Marion",
  "last_name": "Cottilard",
  "known_for": "Shutter Island"
}

### DELETES ACTOR
DELETE POST http://localhost:3000/actors/22.json

