### CREATES A USER

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bruce Lee",
  "email": "b@ex.com",
  "password": "kickass",
  "password_confirmation": "kickass"

}


### CREATES ACTOR
POST http://localhost:3000/actors.json
Content-Type: application/json

{
"first_name": "Gena", 
"last_name": "Rowlands", 
"known_for": "A Woman Under the Influence", 
"gender": "F", 
"age": 91,
"movie_id": 3
}

### UPDATES ACTOR
PATCH http://localhost:3000/actors/34.json
Content-Type: application/json

{ "first_name": "Kelly",
  "last_name": "Kaufman",
  "know_for": "Jacob's Ladder",
  "gender": "F",
  "age": 30,
  "movie_id": 5
}

### DELETES ACTOR
DELETE http://localhost:3000/actors/25.json


### CREATES A MOVIE
POST  http://localhost:3000/movies.json
Content-Type: application/json

{ "title": "",
  "year": 2015, 
  "plot": "While exploring the uncharted wilderness in 1823, frontiersman Hugh Glass sustains life-threatening injuries from a brutal bear attack.",
  "director": "Alejandro González Iñárritu",
  "english": "Yes"}


### UPDATES A MOVIE
# MUST FIX TO SHOW: unprocessible entity
PATCH http://localhost:3000/movies/3.json
Content-Type: application/json

{
  "title": "ChungKing Express",
  "year": 1994,
  "plot": "Every day, Cop buys a can of pineapple with an expiration date of May 1, symbolizing the day he'll get over his lost love.",
  "director": "",
  "english": "No"
}

### DELETES A MOVIE

DELETE http://localhost:3000/movies/2.json


